### ISSUE TITLE
Does this work with the latest NestJS?

### ISSUE THREAD

**Issue by synerp** [charlypoly/graphql-yoga-nestjs#38]
Maybe its just me but I tried it out and received the following error:
[Nest] 29744  - 10/12/2022, 11:01:43 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the YogaDriver. Please make sure that the "graphQlFactory" property is available in the current context.

Potential solutions:
- If GraphQLFactory is a provider, is it part of the current GraphQLModule?
- If GraphQLFactory is exported from a separate @Module, is that module imported within GraphQLModule?
  @Module({
    imports: [ /* the Module containing GraphQLFactory */ ]
  })

**Comment by charlypoly** [comment]
Hi @synerp,

The GraphQL Yoga driver has been written for  Nest `8.4.7`, I work on updating it soon.

**Comment by synerp** [comment]
Thanks!

**Comment by charlypoly** [comment]
Hi @synerp,

I am currently working on upgrading this package to the latest version of NestJS (v9.x) and Yoga (v3).
From what I'm seeing, I'm not even sure that other GraphQL drivers support NestJS (v9.x).

Could you share the version of the NestJS packages that you use?

**Comment by synerp** [comment]
I am using "@nestjs/apollo": "^10.1.3", and  "@nestjs/graphql": "^10.1.3".

**Comment by charlypoly** [comment]
`@nestjs/apollo` is maintained by NestJS people, I encourage you to open an issue on their repository: https://github.com/nestjs/graphql/issues/new?assignees=&labels=needs+triage%2Cbug&template=Bug_report.yml

I think that GraphQL drivers have not yet been updated to be compatible with NestJS `9.x`.

**Comment by synerp** [comment]
@charlypoly Hi Charlie, Sorry but I seem to have misunderstood you.  In response to you saying that no other drivers support v9, I replied that @nestjs/apollo works fine.    I thought you were looking for a working driver for reference.

**Comment by charlypoly** [comment]
Hi @synerp,

Thank you for confirming this; other users also confirmed that other Nest GraphQL drivers are working as expected with Nest 9.
We will continue investigating this issue and keep you updated here!

**Comment by Tchoupinax** [comment]
Hello,
I also met the issue.
Can we help you on that? You have to upgrade the module to be compatible with version 9 of Nest.js?

Thanks!

**Comment by charlypoly** [comment]
Hi @Tchoupinax,

Yeah, we are seeking help on this topic! 👀 
The current implementation has some issues with Nest DI that can happen with Nest 8 but are especially blockers for Nest 9.

I can provide more context by mail or other medium on the inner working of the project.

**Comment by Tchoupinax** [comment]
Hello @charlypoly,
I made a MR to upgrade dependancies and make the plugin working with Nest.js v9. It works well with my project (where I want to use this plugin).

**Comment by synerp** [comment]
I look forward to trying out Yoga v3 with NestJS :)

**Comment by enisdenjo** [comment]
The latest [v0.2.0](https://github.com/charlypoly/graphql-yoga-nestjs/releases/tag/v0.2.0) now supports NestJS version v9. 🎊 

@Tchoupinax @synerp I'd be very thankful if you could try this out!

**Comment by synerp** [comment]
> The latest [v0.2.0](https://github.com/charlypoly/graphql-yoga-nestjs/releases/tag/v0.2.0) now supports NestJS version v9. 🎊
> 
> @Tchoupinax @synerp I'd be very thankful if you could try this out!

I tried and got the same error as https://github.com/charlypoly/graphql-yoga-nestjs/issues/52
