### ISSUE TITLE
DI of GraphQLFederationFactory in YogaFederationDriver not work

### ISSUE THREAD

**Issue by SirReiva** [charlypoly/graphql-yoga-nestjs#48]
if @nest/graphl and @graphql-yoga/nestjs versions missmatch(patch version) Nestjs DI of GraphQLFederationFactory in YogaFederationDriver not found di token.

#49 fix that

**Comment by productdevbook** [comment]
same problem

**Comment by shoaibsharif** [comment]
any ETA to fix this issue?

**Comment by ardatan** [comment]
PRs are welcome to fix the issue.

**Comment by shoaibsharif** [comment]
@ardatan #49 seems a fix?

**Comment by enisdenjo** [comment]
Quick heads up, this has been fixed with #54. Please update to at least `@graphql-yoga/nestjs@v0.3.0` and additionally install `@nestjs/graphql` since it's now a peer dependency.
