### ISSUE TITLE
Newcomer to Nestjs with Yoga

### ISSUE THREAD

**Issue by smolinari** [charlypoly/graphql-yoga-nestjs#76]
Hi,

I tried to migrate my NestJS Fastify/Mercurius app to Yoga and have run into a strange scenario. 

First, I'm getting this noted by the Nest logger, even before everything starts logging for the bootstrap process:

![image](https://user-images.githubusercontent.com/3314957/217187347-f9983bef-a8a8-4d80-897e-9e2076073919.png)

Next, everything compiles and the server runs, but nothing is coming from the server. I get headers back, but no response body. No Graphiql, no introspection. 

Not sure how to dig further. Any tips would be appreciated.

Scott

**Comment by enisdenjo** [comment]
Hey there, sorry to hear you're running in some issues. I'd love to help but I don't know where to start, I need more information about the setup - can you share a reproduction repo, or simply how to run here in this issue? Thanks!

**Comment by smolinari** [comment]
@enisdenjo - Thanks for the reply. I'm going to let this sit for a while i.e. close the issue as I don't have the time to troubleshoot further. When I get some time, I'll come back and try to give a working reproduction repo.  

Scott
