### ISSUE TITLE
Schema first approach with federation

### ISSUE THREAD

**Issue by timkuilman** [charlypoly/graphql-yoga-nestjs#77]
The examples have a directory `graphql-federation-code-first`. I tried hooking up a schema first NestJS application using the Yoga driver but that doesn't seem to work. Does anyone have some lead on how to change a regular schema into a federated schema?  

```Error: Couldn't load service definitions for "<servicename>" at http://localhost:4003/graphql: Cannot query field "_service" on type "Query".```

Looking forward to try out the yoga federation implementation!

**Comment by ardatan** [comment]
Could you create a reproduction? Thanks!
Also make sure you use `buildSubgraphSchema` from `@apollo/subgraph` package in order to create a subgraph schema.

**Comment by timkuilman** [comment]
Thanks, that helped! It was something on my end.
